### PR TITLE
data-pipeline--staging

### PR DESCRIPTION
**Pull request by giorgiosironi**
For https://github.com/elifesciences/issues/issues/4467

Attempting to create this stack, with no success so far.

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Terraform keeps getting this error:
```
data.http.staging_380_datascience_early_career_researchers: Refreshing state...
data.http.staging_489_datascience_editor_keywords: Refreshing state...
data.http.staging_455_datascience_editors: Refreshing state...
data.vault_generic_secret.fastly: Refreshing state...

Error: Error refreshing state: 3 error(s) occurred:

* data.http.staging_380_datascience_early_career_researchers: 1 error(s) occurred:

* data.http.staging_380_datascience_early_career_researchers: data.http.staging_380_datascience_early_career_researchers: HTTP request error. Response code: 404
* data.http.staging_455_datascience_editors: 1 error(s) occurred:

* data.http.staging_455_datascience_editors: data.http.staging_455_datascience_editors: HTTP request error. Response code: 404
* data.http.staging_489_datascience_editor_keywords: 1 error(s) occurred:

* data.http.staging_489_datascience_editor_keywords: data.http.staging_489_datascience_editor_keywords: HTTP request error. Response code: 404
```

In fact these data sources are linking to https://github.com/elifesciences/data-pipeline/schemas/455_datascience_editors.json which is a 404 not found so it is right. /cc @de-code @lsh-0

**Comment by de-code** [comment]
Ah, these have moved to https://github.com/elifesciences/data-pipeline-ejp-csv-deposit/tree/master/schemas (see discussion in https://github.com/elifesciences/data-pipeline/pull/2)

**Comment by giorgiosironi** [comment]
The correct URL is somewhat like https://raw.githubusercontent.com/elifesciences/data-pipeline-ejp-csv-deposit/master/schemas/380_datascience_early_career_researchers.json

**Comment by giorgiosironi** [comment]
Progress:
```
Error: Error applying plan:

3 error(s) occurred:

* google_bigquery_table.staging_380_datascience_early_career_researchers: 1 error(s) occurred:

* google_bigquery_table.staging_380_datascience_early_career_researchers: json: cannot unmarshal object into Go value of type []*bigquery.TableFieldSchema
* google_bigquery_table.staging_489_datascience_editor_keywords: 1 error(s) occurred:

* google_bigquery_table.staging_489_datascience_editor_keywords: json: cannot unmarshal object into Go value of type []*bigquery.TableFieldSchema
* google_bigquery_table.staging_455_datascience_editors: 1 error(s) occurred:

* google_bigquery_table.staging_455_datascience_editors: json: cannot unmarshal object into Go value of type []*bigquery.TableFieldSchema
```

**Comment by giorgiosironi** [comment]
If you compare the schemas to the [ones we have in `builder`](https://github.com/elifesciences/builder/blob/master/src/buildercore/bigquery/schemas/fastly-logs-201809.json) you'll see they have a `fields` subdictionary that is not present here.

Now I would be happy for the projects to manage their own tables and schemas, leaving only the datasets as created by `builder` as the top level of infrastructure as code; assuming they can add/update/migrate/remove them as needed. Should these schemas and tables be dropped from here?

**Comment by de-code** [comment]
> If you compare the schemas to the [ones we have in `builder`](https://github.com/elifesciences/builder/blob/master/src/buildercore/bigquery/schemas/fastly-logs-201809.json) you'll see they have a `fields` subdictionary that is not present here.

My generated schema files in [data-pipeline-ejp-to-json-converter](https://github.com/elifesciences/data-pipeline-ejp-to-json-converter) also look similar to the Fastly logs (starting with the array `[` and it only has `fields` for nested fields).

> Now I would be happy for the projects to manage their own tables and schemas, leaving only the datasets as created by `builder` as the top level of infrastructure as code; assuming they can add/update/migrate/remove them as needed. Should these schemas and tables be dropped from here?

At what point would we create the table in that case? The NiFi CSV pipeline currently just appends to existing tables. The XML pipeline using [data-pipeline-ejp-to-json-converter](https://github.com/elifesciences/data-pipeline-ejp-to-json-converter) currently replaces the table and with that adds it if necessary. But I was thinking whether we should now also create empty tables using the schema, so that views could be created.

**Comment by giorgiosironi** [comment]
> At what point would we create the table in that case? The NiFi CSV pipeline currently just appends to existing tables. The XML pipeline using data-pipeline-ejp-to-json-converter currently replaces the table and with that adds it if necessary. But I was thinking whether we should now also create empty tables using the schema, so that views could be created.

The `data-pipeline-ejp-to-json-converter` will needs its own pipeline that deploys it to the Nifi server and also runs something that updates that particular environment with the latest schema. The basic question to ask is, given a new commit in that repository, how does it get live in `prod`?

**Comment by de-code** [comment]
> The `data-pipeline-ejp-to-json-converter` will needs its own pipeline that deploys it to the Nifi server and also runs something that updates that particular environment with the latest schema. The basic question to ask is, given a new commit in that repository, how does it get live in `prod`?

The `data-pipeline-ejp-to-json-converter` is already deployed to the NiFi pipeline. Although I am still not sure whether it's fully automated but it's via the formula. Is your suggestion that the deployment step of it should also create the empty tables? Similar the deployment of `data-pipeline-ejp-csv-deposit` would create its tables?

**Comment by lsh-0** [comment]
regarding the structure of the schemas, I don't know what the proper format is, I've never had to (or have found) a way of automatically re-creating a bq table from the schema.

I have a script in the root of the project that dumps them for me:
https://github.com/elifesciences/data-pipeline-ejp-csv-deposit/blob/master/update-schemas.sh

(and is, in fact, missing the new table, I'll add that)

**Comment by giorgiosironi** [comment]
So, options:
1. remove the `fields` thing (including from the script's result), use these schemas from `builder`
2. remove the reference to the schemas from builder, possibly also the reference to the table names, creating only the datasets

1 or 2?

**Comment by de-code** [comment]
Using `bq show --schema --format prettyjson <table name>` also returns a schema starting with `[`. It's just confusing that the `schema` property is not returning the same (see [BigQuery schema docs](https://cloud.google.com/bigquery/docs/schemas)).

I'd suggest option 1.

(That's not to say that the schema migration should not be moved, as I'd like my schemas from the XML conversion to be used the same)

**Comment by giorgiosironi** [comment]
I have commented out the schemas and as soon as everything is green I'll open a PR to modify them and reinstate the reference on this branch.

**Comment by giorgiosironi** [comment]
https://github.com/elifesciences/data-pipeline-ejp-csv-deposit/pull/3

**Pull request merged**
