### PR TITLE
Update AMI for 1804 to ami-0cb0ec9b5651415e7

### PR DESCRIPTION
**Pull request by elife-alfred-user**
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-builder-ami-update/6/display/redirect which resulted in this pull request.

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Do we want to do this on a schedule?

**Comment by lsh-0** [comment]
the creation of new AMIs? I think we absolutely should. Extra points if we can also:

* update the project file afterwards
* automatically open a PR and assign a reviewer (just like this)
* add the new LTS when it comes out

**Comment by giorgiosironi** [comment]
Current status:

- [x] update the project file afterwards
- [x] automatically open a PR 
- [ ] and assign a reviewer (just like this)
- [ ] add the new LTS when it comes out

but https://alfred.elifesciences.org/job/process/job/process-basebox-1804/ doesn't run automatically, only on demand.

What should the frequency be? This is implemented for 18.04 but we do support 16.04 so the process should be duplicated for that.

**Comment by lsh-0** [comment]
weekly? monthly? whenever builder-base changes? whenever the base ami changes? I'm not sure. It doesn't need to happen often I think, it's going to affect new instances only which means formula PRs 

I would go with weekly to be honest. That seems just often enough for it to become routine and to shake out the issues peculiar to it.

**Comment by giorgiosironi** [comment]
Set https://alfred.elifesciences.org/job/process/job/process-basebox-1804/ to run weekly on Monday at 3 AM.

**Pull request merged**
