### PR TITLE
Feature: moves elife-bot configuration over to 16.04

### PR DESCRIPTION
**Pull request by lsh-0**
elife-bot has just a few too many issues to deal with right now for a straight 14.04 -> 18.04 upgrade. It works nicely on 16.04 however

* depends on https://github.com/elifesciences/elife-bot-formula/pull/7

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Shouldn't we start upgrading existing instances like `elife-metrics` before porting more projects? There are 10 open PRs now on this repository

**Comment by lsh-0** [comment]
I'm porting the projects to make sure there are no hidden gotchas, like nodejs6 actually installing nodejs8.

My plan is:

* upgrade all instances to new salt version
* merge builder PR that upgrades default ubuntu to 18.04 and pins projects to 14.04/16.04
* finish porting the remaining project formulas (I think there are 4 at time of writing)
* begin porting actual project instances. this is when the PR count for this repo will start going down.

Is there a problem with having a larger than usual number of PRs open while I do this?

**Comment by giorgiosironi** [comment]
Not particularly, but they shouldn't be merged until the state of infrastructure reflects what they prescribe in terms of host version. The plan is consistent with this. I'm also up for the formulas to be supporting multiple OS versions as soon as possible, nothing blocks them.

**Comment by lsh-0** [comment]
just an fyi, elife-bot is building fine on 18.04 so I'll be upgrading it directly to that

**Comment by lsh-0** [comment]
> elife-bot has just a few too many issues to deal with right now for a straight 14.04 -> 18.04 upgrade. It works nicely on 16.04 however

and 

> just an fyi, elife-bot is building fine on 18.04 so I'll be upgrading it directly to that

goddamn, I just messed up

**Pull request merged**
