### PR TITLE
strip whitespace from terraform version check

### PR DESCRIPTION
**Pull request by lsh-0**
Alfred is actually broken until this gets merged in.

### CODE REVIEW

**Comment by lsh-0** [comment]
aaaand github isn't letting me merge until it's passing. dumb dumb dumb. will fix master directly

**Comment by lsh-0** [comment]
aaaand github refuses my push to master.

**Comment by giorgiosironi** [comment]
Good fix, how could this stop working? I saw this error locally while testing a Jenkins upgrade but didn't delve into it in time.

**Comment by lsh-0** [comment]
it became a chicken-egg thing. Builder in `master` became broken as `Terraform` got a new release and `.prerequisites.py` couldn't be run anymore without crashing. The `prerequisites.py` fix couldn't be run because Alfred couldn't execute builder - so literally all builds were broken, I think.

**Comment by lsh-0** [comment]
I then merged this one locally and then got another (the actual) problem and pushed that directly to `master`

**Pull request merged**
