### PR TITLE
Feature: upgrades pattern-library to use Ubuntu 18.04

### PR DESCRIPTION
**Pull request by lsh-0**

### CODE REVIEW

**Comment by lsh-0** [comment]
hrm - `update_infrastructure` for `--ci` and `--prod` say nothing needs updating. Do I need to do something special here to get the ec2 instance replaced? or is it easier to just delete and recreate it?

**Comment by giorgiosironi** [comment]
https://github.com/elifesciences/builder/blob/master/docs/playbooks/upgrade-os-instances.md is a procedure that allows to destroy and recreate the EC2 instance without destroying a stack. In the case of `pattern-library` it doesn't matter much because it's stateless, but it needs to be well rehearsed to be used on `journal-cms`. Destroying the whole stack there would also delete the RDS database and the EBS volume with the uploaded files, prolonging the downtime as they are restored from backups.

**Comment by giorgiosironi** [comment]
`update_infrastructure` by default will ignore changes in the AMI (and a few other EC2 fields) because that will destroy all EC2 instances in our account whenever we update the AMI in `defaults`.

**Comment by lsh-0** [comment]
>  because that will destroy all EC2 instances in our account whenever we update the AMI in defaults.

ah, that makes sense, I felt there had to be a good reason

**Pull request merged**
