### PR TITLE
Turn up the user dial to 100%

### PR DESCRIPTION
**Pull request by diversemix**
This will mean ~64% of total submissions will be coming via xPub

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Applied to `journal--prod`. Have to make the build green before merging.

**Comment by giorgiosironi** [comment]
[Strange error](https://alfred.elifesciences.org/blue/organizations/jenkins/pull-requests-projects%2Fbuilder/detail/PR-465/5/pipeline) in building the Python 3.5 Docker image. @GiancarloFusiello any insight into what that means?

**Comment by GiancarloFusiello** [comment]
> [Strange error](https://alfred.elifesciences.org/blue/organizations/jenkins/pull-requests-projects%2Fbuilder/detail/PR-465/5/pipeline) in building the Python 3.5 Docker image. @GiancarloFusiello any insight into what that means?

@giorgiosironi Taking a look now

**Comment by giorgiosironi** [comment]
Reproduces for me with `./docker-smoke.sh 3`, something may have changed in the Python 3 image we use as `requirements.txt` hasn't been touched for more than a month.

**Comment by diversemix** [comment]
Fails in the same way for me... My tup'ence 'apny ... https://github.com/pypa/pip/issues/6246

**Comment by giorgiosironi** [comment]
Tried downgrading to `python:3.5.5-slim-jessie` (since the current one should be `python:3.5.6-slim-jessie`), but no difference.

**Comment by giorgiosironi** [comment]
Same goes for the `3.5.4` one, so it may not be something in the base image but some package or package version.

**Comment by GiancarloFusiello** [comment]
The problem appears to be with pip. I'm currently trying to install requirements with a downgraded version pip.

**Pull request merged**
