### PR TITLE
Replace some `python` binary calls with `python3`

### PR DESCRIPTION
**Pull request by scottaubrey**
Some local fixes I'm carrying, thought I should get them merged.

### CODE REVIEW

**Comment by lsh-0** [comment]
cheers, @scottaubrey , this looks good.

On my particular flavour of linux `python` points to the latest, but I know on Ubuntu and such it probably assumes Py2

**Review by lsh-0 — APPROVED** [review]

**Comment by scottaubrey** [comment]
Screenshot 2022-09-02 at 7 58 00 am

Wow! pre-cog levels of reflexes there @lsh-0  😆

**Comment by lsh-0** [comment]
within a virtualenv (`venv`) `python` will refer to `venv/bin/python`, which is hopefully `python3.8`:

```
$ ls -l venv/bin/ | grep python
lrwxrwxrwx 1 luke luke     9 Aug 31 12:00 python -> python3.8
lrwxrwxrwx 1 luke luke     9 Aug 31 12:00 python3 -> python3.8
lrwxrwxrwx 1 luke luke    18 Aug 31 12:00 python3.8 -> /usr/bin/python3.8
```

**Comment by scottaubrey** [comment]
> within a virtualenv (`venv`) `python` will refer to `venv/bin/python`, which is hopefully `python3.8`:
> 
> ```
> $ ls -l venv/bin/ | grep python
> lrwxrwxrwx 1 luke luke     9 Aug 31 12:00 python -> python3.8
> lrwxrwxrwx 1 luke luke     9 Aug 31 12:00 python3 -> python3.8
> lrwxrwxrwx 1 luke luke    18 Aug 31 12:00 python3.8 -> /usr/bin/python3.8
> ```

Ah, you are right - the symlinks in my `./venv` is setup the same (though different upstream binary path). 

Looking into it a bit more, I've been assuming the venv got activated when running update.sh, which I run every new terminal. Thinking about it now, it will only source the venv in the scope of that script, not my shell. 🤦‍♂️  Thanks for the pointer, really helpful.

**Comment by lsh-0** [comment]
Yeah, `python` or `python3` after the virtualenv has been sourced should be fine, with `python3` probably safer than `python` as a default.

**Pull request merged**
