### PR TITLE
Add builder-configuration on master servers

### PR DESCRIPTION
**Pull request by giorgiosironi**
Part of https://github.com/elifesciences/issues/issues/3691

The repository is still mostly empty, but it needs to be deployed before it can be referenced further.

### CODE REVIEW

**Comment by giorgiosironi** [comment]
After tests pass, going to try to apply to the real `master-server`.

**Comment by giorgiosironi** [comment]
(probably will take more just to get the tests together)

**Comment by lsh-0** [comment]
I would err on the side of caution. I won't be available until Mon

**Comment by lsh-0** [comment]
I'll merge this in first thing tomorrow so I can handle any problems that might come up

**Comment by lsh-0** [comment]
instance required a `./bldr update_infrastructure` to refresh the instance data ('context') otherwise it would throw a keyerror in `buildercore/bootstrap.py` and we don't seem to have a task for simply refreshing the context. The test instance was only good up to a point, but crashes with an invalid master private key when it tries to run highstate.
The prod master-server applies the changes without issue but I'll keep an eye out for any weirdness

**Comment by giorgiosironi** [comment]
> instance required a ./bldr update_infrastructure to refresh the instance data ('context') 

Makes sense, wouldn't do that for each deployment.

**Pull request merged**
