### PR TITLE
shifts handling of pip and setuptools (easy_install) into bootstrap

### PR DESCRIPTION
**Pull request by lsh-0**
adds a flag that can be used to force an upgrade of python/pip/setuptools

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Trying it out locally now

**Comment by lsh-0** [comment]
you'll need you builder-base on the right branch as well

**Comment by giorgiosironi** [comment]
Good output on first run on 14.04, now stress testing it and checking 16.04 as well.
```
[08:22:00][elife@dev--basebox:~]$ python --version
Python 2.7.14
[08:22:01][elife@dev--basebox:~]$ pip --version
pip 10.0.1 from /usr/local/lib/python2.7/dist-packages/pip (python 2.7)
[08:22:04][elife@dev--basebox:~]$ pip list | grep setuptools
setuptools                    40.0.0 
```

**Comment by lsh-0** [comment]
there shouldn't actually be any problem using `pip.installed` states, I just decided to avoid it in this one instance

**Comment by lsh-0** [comment]
you should disambiguate `pip` there - there are `pip2` and `pip3` executables I think

**Comment by giorgiosironi** [comment]
Same result on `elife-bot-formula` (14.04):
```
elife@dev--elife-bot:~$ python2 --version
Python 2.7.14
elife@dev--elife-bot:~$ pip --version
pip 10.0.1 from /usr/local/lib/python2.7/dist-packages/pip (python 2.7)
elife@dev--elife-bot:~$ pip list | grep setuptools
setuptools                    40.0.0  
```
The full highstate is still running...

**Comment by giorgiosironi** [comment]
Will continue integrating on https://github.com/elifesciences/builder-base-formula/pull/155#issuecomment-405864101

**Pull request merged**
