### PR TITLE
Linting enforcing

### PR DESCRIPTION
**Pull request by giorgiosironi**
I ran .lint.sh and it started to produce all sorts of modifications forgotten from previous commits.

So after this catchup, I think it could be enforced by the build like we do in PHP projects.

### CODE REVIEW

**Comment by giorgiosironi** [comment]
If I execute .lint.sh however, pylint starts to complaining in the build that the changes made by the scrubber violate its constraints...

**Comment by giorgiosironi** [comment]
Steps to reproduce: run .lint.sh twice. Output is:
```
$ ./.lint.sh 
* calling pyflakes
* calling pylint
* scrubbing
* passed linting
$ ./.lint.sh 
* calling pyflakes
* calling pylint
************* Module decorators
C:116,26: More than one statement on a single line (multiple-statements)
************* Module remote_master
C: 43,29: More than one statement on a single line (multiple-statements)
************* Module buildercore.bootstrap
E: 69, 8: function already defined line 64 (function-redefined)
C: 69,24: More than one statement on a single line (multiple-statements)
E: 71, 8: function already defined line 65 (function-redefined)
C: 71,24: More than one statement on a single line (multiple-statements)
************* Module buildercore.core
C:463, 4: Invalid argument name "t" (invalid-name)
C:463,15: More than one statement on a single line (multiple-statements)
```

**Comment by lsh-0** [comment]
ha! I can totally recreate this. strange. let me look into it

**Comment by lsh-0** [comment]
ok, I'm guessing the dep upgrade introduced a fix to an old rule, or a new rule in `autopep8` that caused this extra fix to be done. The extra fix introduced code pylint took umbrage with.

**Pull request merged**
