### PR TITLE
fixes a bug in lifecycle.py where an rds resource is returned instead…

### PR DESCRIPTION
**Pull request by lsh-0**
… of the expected client

### CODE REVIEW

**Comment by giorgiosironi** [comment]
This is the problem in https://alfred.elifesciences.org/job/process-stop-stacks-long-term/ ?

**Comment by lsh-0** [comment]
looks like it

**Comment by lsh-0** [comment]
I suppose it's not covered in any test because of attached rds instance

**Comment by giorgiosironi** [comment]
It takes a long time (>10 minutes sometimes) to stop one of those instances, making automated tests prohibitively slow.

**Comment by giorgiosironi** [comment]
Tested in https://alfred.elifesciences.org/job/process-stop-stacks-long-term/60/console which seems to be running fine for now.

**Pull request merged**
