### PR TITLE
Install docker~=7.1 Python

### PR DESCRIPTION
**Pull request by gnott**
Proposed change to Python `docker` library, I'm not sure how many pipelines would be affected.

### CODE REVIEW

**Comment by gnott** [comment]
After the call with @discodavey, I'm adding some reviewers to this PR for updating the `docker` Python library dependency. I'm not sure how it might affect other projects. I think it may help with resolving issue https://github.com/elifesciences/issues/issues/8897  Thanks for taking a look and considering it!

**Comment by ali-tm-amin** [comment]
It looks okay and we just trying to figure out how to test it. Thanks

**Comment by ali-tm-amin** [comment]
I just tried  `docker~=7.1` on `Vagrant` it failed
```
journal-cms--vagrant: ERROR: Could not find a version that satisfies the requirement docker~=7.1 (from versions: none)
journal-cms--vagrant: ERROR: No matching distribution found for docker~=7.1
```

**Comment by gnott** [comment]
Great to see some output, thanks @ali-tm-amin!

I wonder if the version of this library is pinned to the Debian/Ubuntu distribution, or to Salt?

Anyway, this is probably not the easy win I was hoping for, and feel welcome to close this PR if it's not a viable direction to try.

**Comment by ali-tm-amin** [comment]
If you try a `stable` version `docker~=7.0` it will run and install successfully:
```
 journal-cms--vagrant: # install salt dependencies
    journal-cms--vagrant: # some Salt states require extra libraries to be installed before calling highstate.
    journal-cms--vagrant: # salt builtins: https://github.com/saltstack/salt/blob/master/requirements/static/pkg/py3.9/linux.txt
    journal-cms--vagrant: if ($installing || $upgrading); then
    journal-cms--vagrant:     # lsh@2023-05-12: version pins are just because they're the latest stable, nothing significant.
    journal-cms--vagrant:     salt-pip install "docker~=7.0" "pymysql~=1.0"
    journal-cms--vagrant: fi
    journal-cms--vagrant: + true
    journal-cms--vagrant: + salt-pip install docker~=7.0 pymysql~=1.0
    journal-cms--vagrant: Collecting docker~=7.0
    journal-cms--vagrant:   Downloading docker-7.1.0-py3-none-any.whl.metadata (3.8 kB)
    journal-cms--vagrant: Collecting pymysql~=1.0
    journal-cms--vagrant:   Downloading PyMySQL-1.1.1-py3-none-any.whl.metadata (4.4 kB)
    journal-cms--vagrant: Requirement already satisfied: requests>=2.26.0 in /opt/saltstack/salt/lib/python3.10/site-packages (from docker~=7.0) (2.32.3)
    journal-cms--vagrant: Requirement already satisfied: urllib3>=1.26.0 in /opt/saltstack/salt/lib/python3.10/site-packages (from docker~=7.0) (1.26.18)
    journal-cms--vagrant: Requirement already satisfied: charset-normalizer<4,>=2 in /opt/saltstack/salt/lib/python3.10/site-packages (from requests>=2.26.0->docker~=7.0) (3.2.0)
    journal-cms--vagrant: Requirement already satisfied: idna<4,>=2.5 in /opt/saltstack/salt/lib/python3.10/site-packages (from requests>=2.26.0->docker~=7.0) (3.7)
    journal-cms--vagrant: Requirement already satisfied: certifi>=2017.4.17 in /opt/saltstack/salt/lib/python3.10/site-packages (from requests>=2.26.0->docker~=7.0) (2024.7.4)
    journal-cms--vagrant: Downloading docker-7.1.0-py3-none-any.whl (147 kB)
    journal-cms--vagrant:    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 147.8/147.8 kB 4.9 MB/s eta 0:00:00
    journal-cms--vagrant: Downloading PyMySQL-1.1.1-py3-none-any.whl (44 kB)
    journal-cms--vagrant:    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.0/45.0 kB 7.5 MB/s eta 0:00:00
    journal-cms--vagrant: Installing collected packages: pymysql, docker
    journal-cms--vagrant: Successfully installed docker pymysql
```



> Great to see some output, thanks @ali-tm-amin!
> 
> I wonder if the version of this library is pinned to the Debian/Ubuntu distribution, or to Salt?
> 
> Anyway, this is probably not the easy win I was hoping for, and feel welcome to close this PR if it's not a viable direction to try.

Regarding your question, I'm guessing it's pinned to [salt](https://github.com/elifesciences/builder-base-formula/blob/9a0f8d2509c7dfe059a8a248400182e57e3e55de/salt/elife/docker-native.sls#L37-L46)

**Comment by gnott** [comment]
Looks even better!

In the end it installed the version `7.1.0` anyway (https://pypi.org/project/docker/7.1.0/), which is stable as far as I know.

I think https://github.com/elifesciences/builder-base-formula/blob/9a0f8d2509c7dfe059a8a248400182e57e3e55de/salt/elife/docker-native.sls#L37-L46 is possibly referring to the `docker` executable? I'm trying to update the Python library named `docker`.

**Comment by ali-tm-amin** [comment]
We encounter similar issue in `iiif-formula` and so we need to update this for that formula.
Reading through the change logs the changes between 6.9.0 and 7.1.0 don't look like affect us. So we decided to merge it and deal with the consequences if there any.

**Pull request merged**
