### PR TITLE
Threadbare backend

### PR DESCRIPTION
**Pull request by lsh-0**
changes default backend to threadbare

### CODE REVIEW

**Comment by giorgiosironi** [comment]
I'm still supposed to use Python 2 to test this right?

**Comment by giorgiosironi** [comment]
Uhm `./update.sh`:
```
ERROR: Package 'setuptools' requires a different Python: 2.7.12 not in '>=3.5'
```

Jenkins is still on 2.7 though so this should work for me:
```
jenkins@prod--alfred:/srv/builder$ venv/bin/python --version
Python 2.7.12
jenkins@prod--alfred:/srv/builder$ git log
commit 96c42bf35437fd33830f55230ed7f3861aed00bc
Merge: 00d9269 3e3f7a6
Author: LSH <lsh-0@users.noreply.github.com>
Date:   Fri Jan 31 16:42:36 2020 +1030
```

**Comment by giorgiosironi** [comment]
Looks like my `setuptools` was too new, as it was hijacked by certbot:
```
Removing python-setuptools (33.1.1-1+certbot~xenial+1) ...
```
Solution: don't use certbot which changes your OS Python packages.

**Comment by giorgiosironi** [comment]
Looks like the virtualenv is using `setuptools==45.0.0`, completely separate from the OS one, whereas Jenkins has `44.0.0`.

**Comment by giorgiosironi** [comment]
Things like `BLDR_BACKEND=threadbare bldr update:digests--continuumtest` seem to work on a simple 1-server stack.

**Comment by lsh-0** [comment]
> I'm still supposed to use Python 2 to test this right?

works with both Py2 and Py3

> ERROR: Package 'setuptools' requires a different Python: 2.7.12 not in '>=3.5'

haven't seen that one yet. 

I was getting a 'gevent is not installed' on Friday but that was solved by simply running `./update.sh`

> seem to work on a simple 1-server stack.

I've been using it for a while and haven't seen a bug in ages. I'm keen to know any cases I've missed.

**Comment by giorgiosironi** [comment]
Have been using it today but mostly for `update_infrastructure` tasks which don't do much SSH work. Still need to try on Alfred, feel free to SSH in and test from `/srv/builder/` after a `sudo su - jenkins`.

**Comment by lsh-0** [comment]
take your time, no rush.

I've re-discovered pdoc (now pdoc3) and am experimenting with it to generate documentation. I think docs for threadbare will be quite important. They were with Fabric

**Comment by giorgiosironi** [comment]
Noticed a strange log message:
```
INFO - buildercore.command - uploading ? bytes to /etc/cfn-info.json
```
but working well for multi-server *serial* deployment.

**Comment by giorgiosironi** [comment]
The missing decoration of the output can prove problematic in multi-server stacks though, because you cannot guess which server output comes from:
```
BLDR_BACKEND=fabric bldr cmd:search--end2end,"ls -l",concurrency=parallel
...
[54.198.190.74] Executing task 'single_node_work'
[35.153.232.132] Executing task 'single_node_work'
[35.153.232.132] run: ls -l
[54.198.190.74] run: ls -l
[35.153.232.132] out: total 0
[35.153.232.132] out: 

[54.198.190.74] out: total 0
[54.198.190.74] out: 
```
becomes
```
BLDR_BACKEND=threadbare bldr cmd:search--end2end,"ls -l",concurrency=parallel
...
total 0
total 0
```
`run: ` perhaps it's just a separate log and could be on stderr. But the `[ip-address]` prefix is actually useful to have.

**Comment by giorgiosironi** [comment]
Performance comparison:
```
BLDR_BACKEND=threadbare time bldr switch_revision_update_instance:search--end2end,approved,concurrency=serial
3.83user 0.45system 3:03.79elapsed 2%CPU (0avgtext+0avgdata 108512maxresident)k
```
```
BLDR_BACKEND=threadbare time bldr switch_revision_update_instance:search--end2end,approved,concurrency=parallel
4.55user 0.67system 2:19.49elapsed 3%CPU (0avgtext+0avgdata 105972maxresident)k
```
Fabric:
```
BLDR_BACKEND=fabric time bldr switch_revision_update_instance:search--end2end,approved,concurrency=serial
```
```
BLDR_BACKEND=fabric time bldr switch_revision_update_instance:search--end2end,approved,concurrency=serial
19.09user 1.45system 2:04.61elapsed 16%CPU (0avgtext+0avgdata 115268maxresident)k
```
```
BLDR_BACKEND=fabric time bldr switch_revision_update_instance:search--end2end,approved,concurrency=parallel
21.29user 1.80system 1:40.76elapsed 22%CPU (0avgtext+0avgdata 107104maxresident)k
```

Parallel better than serial, but performance penalty. May be just random so doing more testing.

**Comment by giorgiosironi** [comment]
Testing with `BLDR_BACKEND=threadbare time bldr cmd:search--end2end,sleep 20,concurrency=parallel` and similar sees same performance with the two backends.

**Comment by giorgiosironi** [comment]
Deployments fine from `elife-alfred--prod`.

**Comment by giorgiosironi** [comment]
```
docker build --pull -f Dockerfile -t elifesciences/basex-validator:2d358c4f-null . --build-arg schema_version=null=null
```
needs tweaking.

**Comment by giorgiosironi** [comment]
Deleted comment on wrong PR.

**Comment by lsh-0** [comment]
> INFO - buildercore.command - uploading ? bytes to /etc/cfn-info.json

that's the first time you've noticed that?? it's a python2-ism that happened after I downgraded the newly upgraded builder when we discovered it was being really slow. There was some issue making that byte counting python2+3 incompatible so I just left it with a "?".

https://github.com/elifesciences/builder/blob/master/src/buildercore/command.py#L160

I notice it all the time and it bugs me ;)

> The missing decoration of the output can prove problematic in multi-server stacks though, because you cannot guess which server output comes from:

I can remedy this. I'd much rather we pick and choose what to include and when. In this case turning on logging for certain operations. Must work with parallel operations.

> and similar sees same performance with the two backends.

This was my experience, too. Threadbare doesn't take advantage of the parallel capabilities of `ParallelSSH` because they are just plain incompatible with the Fabric idiom we work with, I suspect they're probably faster though. 

Uploading and downloading files is very slow, but that is an sftp thing. I have plans to switch it out for scp if I can do it transparently.

You should probably also check against running a heavy highstate which is why we kept builder back on py2 to begin with.

**Comment by lsh-0** [comment]
line formatting PR here: https://github.com/elifesciences/threadbare/pull/28

**Comment by lsh-0** [comment]
regarding this:

> The missing decoration of the output can prove problematic in multi-server stacks though, because you cannot guess which server output comes from:

> BLDR_BACKEND=fabric bldr cmd:search--end2end,"ls -l",concurrency=parallel

the threadbare backend now looks like:
```
18.234.192.179  out: total 0
52.90.232.31    out: total 0
```

I noticed the commands themselves are not being output. Let me know if you miss that

**Comment by giorgiosironi** [comment]
> I noticed the commands themselves are not being output. Let me know if you miss that 

Could be useful when they are buried inside an `highstate`. Will test some deployments.

**Comment by giorgiosironi** [comment]
Having some problems on deployment. Reducing it to:
```
bldr switch_revision_update_instance:search--continuumtest,approved
...
54.221.28.185   out: Collecting pip
54.221.28.185   out:   Downloading https://files.pythonhosted.org/packages/54/0c/d01aa759fdc501a58f431eb594a17495f15b88da142ce1
4b5845662c13f3/pip-20.0.2-py2.py3-none-any.whl (1.4MB)
exception while executing task 'switch_revision_update_instance': 'ascii' codec can't encode character u'\u258e' in position 10
: ordinal not in range(128)

Traceback (most recent call last):
  File "src/taskrunner.py", line 218, in exec_task
    return_map['result'] = task_map['fn'](*task_args, **task_kwargs)
  File "/home/giorgio/code/builder/src/decorators.py", line 80, in call
    return func(stackname, *args, **kwargs)
  File "/home/giorgio/code/builder/src/deploy.py", line 18, in switch_revision_update_instance
    bootstrap.update_stack(stackname, service_list=['ec2'], concurrency=concurrency_for(stackname, concurrency))
  File "/home/giorgio/code/builder/src/buildercore/bootstrap.py", line 398, in update_stack
    fn(stackname, context, **actual_arguments)
  File "/home/giorgio/code/builder/src/buildercore/context_handler.py", line 84, in decorated_with_only_if
    return fn(stackname, context, **kwargs)
  File "/home/giorgio/code/builder/src/buildercore/decorators.py", line 18, in _wrapper
    return func(stackname, *args, **kwargs)
  File "/home/giorgio/code/builder/src/buildercore/bootstrap.py", line 549, in update_ec2_stack
    stack_all_ec2_nodes(stackname, _update_ec2_node, username=BOOTSTRAP_USER, concurrency=concurrency)
  File "/home/giorgio/code/builder/src/buildercore/core.py", line 370, in stack_all_ec2_nodes
    return serial_work(single_node_work, params)
  File "/home/giorgio/code/builder/src/buildercore/core.py", line 382, in serial_work
    return execute(serial(single_node_work), hosts=list(params['public_ips'].values()))
  File "/home/giorgio/code/builder/src/buildercore/threadbare/execute.py", line 222, in execute_with_hosts
    results = execute(func, param_key="host_string", param_values=host_list)
  File "/home/giorgio/code/builder/src/buildercore/threadbare/execute.py", line 202, in execute
    return _serial_execution(func, param_key, param_values)
  File "/home/giorgio/code/builder/src/buildercore/threadbare/execute.py", line 151, in _serial_execution
    result_list.append(func())
  File "/home/giorgio/code/builder/src/buildercore/threadbare/execute.py", line 15, in inner
    return func(*args, **kwargs)
  File "/home/giorgio/code/builder/src/buildercore/core.py", line 343, in single_node_work
    return workfn(**work_kwargs)
  File "/home/giorgio/code/builder/src/buildercore/bootstrap.py", line 508, in _update_ec2_node
    run_script('bootstrap.sh', salt_version, minion_id, install_master_flag, master_ip, **environment_vars)
  File "/home/giorgio/code/builder/venv/local/lib/python2.7/site-packages/backoff/_sync.py", line 99, in retry
    ret = target(*args, **kwargs)
  File "/home/giorgio/code/builder/src/buildercore/bootstrap.py", line 54, in run_script
    result = remote_sudo(" ".join(env_string + cmd))
  File "/home/giorgio/code/builder/src/buildercore/threadbare/operations.py", line 371, in remote_sudo
    return remote(command, **kwargs)
  File "/home/giorgio/code/builder/src/buildercore/threadbare/operations.py", line 331, in remote
    stdout = _process_output(sys.stdout, result["stdout"], **output_kwargs)
  File "/home/giorgio/code/builder/src/buildercore/threadbare/operations.py", line 250, in _process_output
    new_results = [_print_line(output_pipe, line, **kwargs) for line in result_list]
  File "/home/giorgio/code/builder/src/buildercore/threadbare/operations.py", line 237, in _print_line
    output_pipe.write(template.format(**template_kwargs))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u258e' in position 10: ordinal not in range(128)
```
Seems reproducible. Was seeing the problem also in the parallel case (`concurrency=parallel`), but the error was hidden.

**Comment by lsh-0** [comment]
ooh - a bug. or at least an incompatibility with how we've been using Fabric. I'll get on it

**Comment by lsh-0** [comment]
fix here: https://github.com/elifesciences/builder/pull/619

**Comment by lsh-0** [comment]
some basic timings using this command and python 3.5:

    $ time BLDR_BACKEND=fabric ./bldr cfn.highstate:lax--prod,2

fabric backend, first run:

* output still chunks along slowly
* laptop fan goes crazy
    - cpu 100%

```
INFO - buildercore.bootstrap - Executed script highstate.sh in 233.5754 seconds
Disconnecting from ubuntu@54.85.117.153... done.

real	3m55.585s
user	2m14.233s
sys	0m0.899s
```

---

fabric backend, second run:
```
INFO - buildercore.bootstrap - Executed script highstate.sh in 253.9798 seconds
Disconnecting from ubuntu@54.85.117.153... done.

real	4m16.691s
user	2m35.397s
sys	0m0.705s
```
---

switching backends with:

    time BLDR_BACKEND=threadbare ./bldr cfn.highstate:lax--prod,2

threadbare backend, third run:

* gorgeously silent (laptop didn't even register it running)

```
INFO - buildercore.bootstrap - Executed script highstate.sh in 104.3118 seconds

real	1m46.760s
user	0m1.166s
sys	0m0.105s
```

---

threadbare backend, fourth run:

```
INFO - buildercore.bootstrap - Executed script highstate.sh in 114.0902 seconds

real	1m56.354s
user	0m1.113s
sys	0m0.157s
```

**Comment by lsh-0** [comment]
I'm happy to switch backends now and deal with any threadbare issues as they come along.

**Comment by giorgiosironi** [comment]
Re-testing the problem from https://github.com/elifesciences/builder/pull/607#issuecomment-585774862 on `master`, and it seems gone.

**Comment by giorgiosironi** [comment]
Please merge and let's deal with any fallout.

**Pull request merged**
