### PR TITLE
Allow Alfred to run master.update

### PR DESCRIPTION
**Pull request by giorgiosironi**
In https://alfred.elifesciences.org/job/process-master-server/5/console which was run on-demand before but could become a daily/weekly thing.

### CODE REVIEW

**Comment by lsh-0** [comment]
don't quite get why you're removing a task decorator here

**Comment by giorgiosironi** [comment]
Ah, it has to be substituted with @task rather than removed. Alfred isn't allowed to run `@debugtask`s.

**Comment by lsh-0** [comment]
ah, no problems.

I wonder if I didn't get too obscure with those decorators. Ian was getting on my case about the output of ./bldr being filled with things he (or anyone looking at builder) shouldn't be using so I made the 'debugtask' for admin type stuff. Alfred can run those jobs with the envvar `BLDR_ROLE=admin`

**Comment by giorgiosironi** [comment]
It is true some things require a savvy human (`update_infrastructure` comes to mind), so I'll leave it incapable of running @debugtask.

**Pull request merged**
