### PR TITLE
remove libero editor resources

### PR DESCRIPTION
**Pull request by NuclearRedeye**

### CODE REVIEW

**Comment by NuclearRedeye** [comment]
@lsh-0 some context, just cleaning up the no longer needed staging and production infrastructure for libero-editor. It's already been removed from the kubernetes cluster, hence just need to cleanup the builder managed resources.

What I need to do with this PR is...
- [ ] Remove all s3 buckets named `prod---elife-libero-editor` and `staging--elife-libero-editor`.
- [ ] Remove the SNS queues created to monitor the `elife-production-processes` bucket.

What I _don't_ want to do is delete the `elife-production-processes` bucket. This bucket was created well before editor and is used by the production team.

I believe this PR covers that, but want to be sure before it's merged.

Also, once ready to be merged what's the correct way to destroy the resources?

**Comment by lsh-0** [comment]
`projects/elife.yaml` are just descriptions of projects, not the instances (cloudformation or terraform resources) themselves.

In order to delete an instance of a project, we need the project definition.

To delete an instance of a project we use:

    ./bldr destroy:project--instanceid

So in the case of the 'staging' instance of 'elife-libero-editor' (named `elife-libero-editor--staging`) we'd do:

    ./bldr destroy:elife-libero-editor--staging

> What I don't want to do is delete the elife-production-processes bucket. This bucket was created well before editor and is used by the production team.

If a resource is not part of the Cloudformation/Terraform resource stack, it won't be affected.

I've taken a look at the `staging` stack and there is nothing that can't be deleted from you said:

Screenshot at 2022-04-01 14-57-35

same for the `prod` stack:

Screenshot at 2022-04-01 14-58-26

To delete `prod` resources you need to remove yourself from the `TechTeamDevelopers` group:

Screenshot at 2022-04-01 15-00-19

And then add yourself back in afterwards. It prevents us from accidentally deleting things.

I'm happy to do all this for you and then merge this PR on Monday, just say the word.

**Comment by NuclearRedeye** [comment]
> I'm happy to do all this for you and then merge this PR on Monday, just say the word.

The word is given. Warp speed!

**Comment by lsh-0** [comment]
My partner is a Wrath of Khan person, I'm more of a Search for Spock person.

I'll get this sorted today.

**Comment by lsh-0** [comment]
`staging` and `prod` both failed to delete.

staging left behind:
Screenshot at 2022-04-04 11-49-13

and prod left behind:
Screenshot at 2022-04-04 11-49-56

staging
1. disabled deletion protection on the docdb cluster
2. manually emptying s3 bucket 'staging-elife-libero-editor' ... done.
3. manually deleted cloudformation stack ... done

prod
1. manually emptying s3 bucket 'prod-elife-libero-editor' ... done.
2. manually deleted cloudformation stack ... done.

all good. Emptying the buckets was a bit fussy but we got there in the end.

**Comment by lsh-0** [comment]
oops, this is a PR, not an issue. I'll merge it in now

**Review by lsh-0 — APPROVED** [review]

**Pull request merged**
