### PR TITLE
#5147 add public editor profile table to the bigquery table schema in elife.yaml

### PR DESCRIPTION
**Pull request by tayowonibi**
added public_editor_profile schema to the bigquery data tables schema
@giorgiosironi - can you help review this.
thanks

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Lengthy diffs, perhaps because of the annoying problem of the changing order of fields. Take a look at these and tell me if they do what you expect:
[ci.txt](https://github.com/elifesciences/builder/files/3712107/ci.txt)
[staging.txt](https://github.com/elifesciences/builder/files/3712102/staging.txt)
[prod.txt](https://github.com/elifesciences/builder/files/3712101/prod.txt)

**Comment by de-code** [comment]
Thank you.

Looking at the diffs:
- `ci`
  - most tables have really just changed the order of the fields or new fields hadn't been applied yet (okay to apply), except
  - `google_bigquery_table.ci_annotations`: delete the table? because it's not listed but present? I think that is probably another table that should have been in the builder config then. How come it doesn't seem to want to delete the table in `staging`?
- `staging` and `prod`:
  - it shows `google_bigquery_table.staging_public_editor_profile` as new table even though it already exists, will that fail?

**Comment by de-code** [comment]
I also noticed that the first CSV links point to the archived project. I will change that and add annotations.

**Comment by giorgiosironi** [comment]
> it shows google_bigquery_table.staging_public_editor_profile as new table even though it already exists, will that fail?

It's existing but not in Terraform's state, I think this will need a `terraform import`.

**Comment by de-code** [comment]
> It's existing but not in Terraform's state, I think this will need a `terraform import`.

Are you happy to do that or will that be more time consuming? If all fails, we could probably be okay just re-creating the table (after creating a backup copy).

**Comment by giorgiosironi** [comment]
New diff:
[ci.txt](https://github.com/elifesciences/builder/files/3712659/ci.txt)
[staging.txt](https://github.com/elifesciences/builder/files/3712661/staging.txt)
[prod.txt](https://github.com/elifesciences/builder/files/3712660/prod.txt)
Which environments should I apply? (considering the already existing resources not shown in the diff will be `terraform import`ed manually)

**Comment by de-code** [comment]
Definitely apply to `ci` please.

`staging` and `prod` should be fine too (assuming that adding tables over existing ones is fine after `terraform import`). I also just copied all of the `prod` tables to `de_dev` (as I occasionally do anyway).

**Comment by giorgiosironi** [comment]
Let's do this.

**Comment by giorgiosironi** [comment]
Nope:
```
$ terraform import google_bigquery_table.staging_public_editor_profile elife-data-pipeline:staging.public_editor_profile

Error: Provider "google" depends on non-var "data.vault_generic_secret.gcp.0/data.vault_generic_secret.gcp.N". Providers for import can currently
only depend on variables or must be hardcoded. You can stop import
from loading configurations by specifying `-config=""`.
```

**Comment by de-code** [comment]
I missed two tables being deleted from `ci`. I have added them now as well: `people_orcid_profile` and `people_staff_profile`

Would you mind applying `ci` again?

If `staging` and `prod` proof more difficult and you are busy then we could also delay that (but would need to be solved soon anyway).

**Comment by giorgiosironi** [comment]
Working around `staging` by editing the GCP provider configuration to omit `credentials` and using my laptop ones.

Then reapplying both `ci` and `staging`.

**Comment by giorgiosironi** [comment]
And of course it fails again on `staging` because the tables are already there created outside Terraform. Redoing the workaround...

**Comment by giorgiosironi** [comment]
On `staging` it wants to destroy and recreate these two new tables:
```
-/+ google_bigquery_table.staging_people_orcid_profile (new resource required)
      id:                        "elife-data-pipeline:staging.people_orcid_profile" => <computed> (forces new resource)
      creation_time:             "1560249073681" => <computed>
      dataset_id:                "staging" => "staging"
      etag:                      "WXIBpvi4cJzE/KIKu0B20Q==" => <computed>
      expiration_time:           "0" => <computed>
      last_modified_time:        "1570645470260" => <computed>
      location:                  "US" => <computed>
      num_bytes:                 "59285515" => <computed>
      num_long_term_bytes:       "10845965" => <computed>
      num_rows:                  "846682" => <computed>
      project:                   "elife-data-pipeline" => "elife-data-pipeline"
      schema:                    "[{\"mode\":\"NULLABLE\",\"name\":\"id\",\"type\":\"STRING\"},{\"fields\":[{\"mode\":\"NULLABLE\",\"name\":\"index\",\"type\":\"STRING\"},{\"mode\":\"NULLABLE\",\"name\":\"preferred\",\"type\":\"STRING\"}],\"mode\":\"NULLABLE\",\"name\":\"name\",\"type\":\"RECORD\"},{\"mode\":\"NULLABLE\",\"name\":\"orcid\",\"type\":\"STRING\"},{\"mode\":\"NULLABLE\",\"name\":\"imported_timestamp\",\"type\":\"TIMESTAMP\"}]" => "[{\"mode\":\"NULLABLE\",\"name\":\"id\",\"type\":\"STRING\"},{\"fields\":[{\"mode\":\"NULLABLE\",\"name\":\"index\",\"type\":\"STRING\"},{\"mode\":\"NULLABLE\",\"name\":\"preferred\",\"type\":\"STRING\"}],\"mode\":\"NULLABLE\",\"name\":\"name\",\"type\":\"RECORD\"},{\"mode\":\"NULLABLE\",\"name\":\"orcid\",\"type\":\"STRING\"},{\"mode\":\"NULLABLE\",\"name\":\"imported_timestamp\",\"type\":\"TIMESTAMP\"}]"
      self_link:                 "https://www.googleapis.com/bigquery/v2/projects/elife-data-pipeline/datasets/staging/tables/people_orcid_profile" => <computed>
      table_id:                  "people_orcid_profile" => "people_orcid_profile"
      time_partitioning.#:       "1" => "0"
      time_partitioning.0.field: "imported_timestamp" => "" (forces new resource)
      time_partitioning.0.type:  "DAY" => ""
      type:                      "TABLE" => <computed>

-/+ google_bigquery_table.staging_people_staff_profile (new resource required)
      id:                        "elife-data-pipeline:staging.people_staff_profile" => <computed> (forces new resource)
      creation_time:             "1560249107210" => <computed>
      dataset_id:                "staging" => "staging"
      etag:                      "ftkTIuROChgcUobhSdJ+5g==" => <computed>
      expiration_time:           "0" => <computed>
      last_modified_time:        "1570645426285" => <computed>
      location:                  "US" => <computed>
      num_bytes:                 "22804497" => <computed>
      num_long_term_bytes:       "5762231" => <computed>
      num_rows:                  "35603" => <computed>
      project:                   "elife-data-pipeline" => "elife-data-pipeline"
      schema:                    "[{\"mode\":\"NULLABLE\",\"name\":\"orcid\",\"type\":\"STRING\"},{\"mode\":\"NULLABLE\",\"name\":\"id\",\"type\":\"STRING\"},{\"fields\":[{\"mode\":\"NULLABLE\",\"name\":\"givenNames\",\"type\":\"STRING\"},{\"mode\":\"NULLABLE\",\"name\":\"index\",\"type\":\"STRING\"},{\"mode\":\"NULLABLE\",\"name\":\"preferred\",\"type\":\"STRING\"},{\"mode\":\"NULLABLE\",\"name\":\"surname\",\"type\":\"STRING\"}],\"mode\":\"NULLABLE\",\"name\":\"name\",\"type\":\"RECORD\"},{\"fields\":[{\"fields\":[{\"fields\":[{\"mode\":\"NULLABLE\",\"name\":\"country\",\"type\":\"STRING\"}],\"mode\":\"NULLABLE\",\"name\":\"components\",\"type\":\"RECORD\"},{\"mode\":\"REPEATED\",\"name\":\"formatted\",\"type\":\"STRING\"}],\"mode\":\"NULLABLE\",\"name\":\"address\",\"type\":\"RECORD\"},{\"mode\":\"REPEATED\",\"name\":\"name\",\"type\":\"STRING\"}],\"mode\":\"REPEATED\",\"name\":\"affiliations\",\"type\":\"RECORD\"},{\"fields\":[{\"mode\":\"NULLABLE\",\"name\":\"text\",\"type\":\"STRING\"},{\"mode\":\"NULLABLE\",\"name\":\"type\",\"type\":\"STRING\"}],\"mode\":\"REPEATED\",\"name\":\"profile\",\"type\":\"RECORD\"},{\"mode\":\"NULLABLE\",\"name\":\"competingInterests\",\"type\":\"STRING\"},{\"fields\":[{\"mode\":\"NULLABLE\",\"name\":\"id\",\"type\":\"STRING\"},{\"mode\":\"NULLABLE\",\"name\":\"label\",\"type\":\"STRING\"}],\"mode\":\"NULLABLE\",\"name\":\"type\",\"type\":\"RECORD\"},{\"fields\":[{\"mode\":\"NULLABLE\",\"name\":\"alt\",\"type\":\"STRING\"},{\"fields\":[{\"mode\":\"NULLABLE\",\"name\":\"x\",\"type\":\"INTEGER\"},{\"mode\":\"NULLABLE\",\"name\":\"y\",\"type\":\"INTEGER\"}],\"mode\":\"NULLABLE\",\"name\":\"focalPoint\",\"type\":\"RECORD\"},{\"fields\":[{\"mode\":\"NULLABLE\",\"name\":\"height\",\"type\":\"INTEGER\"},{\"mode\":\"NULLABLE\",\"name\":\"width\",\"type\":\"INTEGER\"}],\"mode\":\"NULLABLE\",\"name\":\"size\",\"type\":\"RECORD\"},{\"fields\":[{\"mode\":\"NULLABLE\",\"name\":\"filename\",\"type\":\"STRING\"},{\"mode\":\"NULLABLE\",\"name\":\"mediaType\",\"type\":\"STRING\"},{\"mode\":\"NULLABLE\",\"name\":\"uri\",\"type\":\"STRING\"}],\"mode\":\"NULLABLE\",\"name\":\"source\",\"type\":\"RECORD\"},{\"mode\":\"NULLABLE\",\"name\":\"uri\",\"type\":\"STRING\"}],\"mode\":\"NULLABLE\",\"name\":\"image\",\"type\":\"RECORD\"},{\"fields\":[{\"fields\":[{\"mode\":\"NULLABLE\",\"name\":\"id\",\"type\":\"STRING\"},{\"mode\":\"NULLABLE\",\"name\":\"name\",\"type\":\"STRING\"}],\"mode\":\"REPEATED\",\"name\":\"expertises\",\"type\":\"RECORD\"},{\"mode\":\"REPEATED\",\"name\":\"focuses\",\"type\":\"STRING\"},{\"mode\":\"REPEATED\",\"name\":\"organisms\",\"type\":\"STRING\"}],\"mode\":\"NULLABLE\",\"name\":\"research\",\"type\":\"RECORD\"},{\"mode\":\"NULLABLE\",\"name\":\"imported_timestamp\",\"type\":\"TIMESTAMP\"}]" => "[{\"mode\":\"NULLABLE\",\"name\":\"orcid\",\"type\":\"STRING\"},{\"mode\":\"NULLABLE\",\"name\":\"id\",\"type\":\"STRING\"},{\"fields\":[{\"mode\":\"NULLABLE\",\"name\":\"givenNames\",\"type\":\"STRING\"},{\"mode\":\"NULLABLE\",\"name\":\"index\",\"type\":\"STRING\"},{\"mode\":\"NULLABLE\",\"name\":\"preferred\",\"type\":\"STRING\"},{\"mode\":\"NULLABLE\",\"name\":\"surname\",\"type\":\"STRING\"}],\"mode\":\"NULLABLE\",\"name\":\"name\",\"type\":\"RECORD\"},{\"fields\":[{\"fields\":[{\"fields\":[{\"mode\":\"NULLABLE\",\"name\":\"country\",\"type\":\"STRING\"}],\"mode\":\"NULLABLE\",\"name\":\"components\",\"type\":\"RECORD\"},{\"mode\":\"REPEATED\",\"name\":\"formatted\",\"type\":\"STRING\"}],\"mode\":\"NULLABLE\",\"name\":\"address\",\"type\":\"RECORD\"},{\"mode\":\"REPEATED\",\"name\":\"name\",\"type\":\"STRING\"}],\"mode\":\"REPEATED\",\"name\":\"affiliations\",\"type\":\"RECORD\"},{\"fields\":[{\"mode\":\"NULLABLE\",\"name\":\"text\",\"type\":\"STRING\"},{\"mode\":\"NULLABLE\",\"name\":\"type\",\"type\":\"STRING\"}],\"mode\":\"REPEATED\",\"name\":\"profile\",\"type\":\"RECORD\"},{\"mode\":\"NULLABLE\",\"name\":\"competingInterests\",\"type\":\"STRING\"},{\"fields\":[{\"mode\":\"NULLABLE\",\"name\":\"id\",\"type\":\"STRING\"},{\"mode\":\"NULLABLE\",\"name\":\"label\",\"type\":\"STRING\"}],\"mode\":\"NULLABLE\",\"name\":\"type\",\"type\":\"RECORD\"},{\"fields\":[{\"mode\":\"NULLABLE\",\"name\":\"alt\",\"type\":\"STRING\"},{\"fields\":[{\"mode\":\"NULLABLE\",\"name\":\"x\",\"type\":\"INTEGER\"},{\"mode\":\"NULLABLE\",\"name\":\"y\",\"type\":\"INTEGER\"}],\"mode\":\"NULLABLE\",\"name\":\"focalPoint\",\"type\":\"RECORD\"},{\"fields\":[{\"mode\":\"NULLABLE\",\"name\":\"height\",\"type\":\"INTEGER\"},{\"mode\":\"NULLABLE\",\"name\":\"width\",\"type\":\"INTEGER\"}],\"mode\":\"NULLABLE\",\"name\":\"size\",\"type\":\"RECORD\"},{\"fields\":[{\"mode\":\"NULLABLE\",\"name\":\"filename\",\"type\":\"STRING\"},{\"mode\":\"NULLABLE\",\"name\":\"mediaType\",\"type\":\"STRING\"},{\"mode\":\"NULLABLE\",\"name\":\"uri\",\"type\":\"STRING\"}],\"mode\":\"NULLABLE\",\"name\":\"source\",\"type\":\"RECORD\"},{\"mode\":\"NULLABLE\",\"name\":\"uri\",\"type\":\"STRING\"}],\"mode\":\"NULLABLE\",\"name\":\"image\",\"type\":\"RECORD\"},{\"fields\":[{\"fields\":[{\"mode\":\"NULLABLE\",\"name\":\"id\",\"type\":\"STRING\"},{\"mode\":\"NULLABLE\",\"name\":\"name\",\"type\":\"STRING\"}],\"mode\":\"REPEATED\",\"name\":\"expertises\",\"type\":\"RECORD\"},{\"mode\":\"REPEATED\",\"name\":\"focuses\",\"type\":\"STRING\"},{\"mode\":\"REPEATED\",\"name\":\"organisms\",\"type\":\"STRING\"}],\"mode\":\"NULLABLE\",\"name\":\"research\",\"type\":\"RECORD\"},{\"mode\":\"NULLABLE\",\"name\":\"imported_timestamp\",\"type\":\"TIMESTAMP\"}]"
      self_link:                 "https://www.googleapis.com/bigquery/v2/projects/elife-data-pipeline/datasets/staging/tables/people_staff_profile" => <computed>
      table_id:                  "people_staff_profile" => "people_staff_profile"
      time_partitioning.#:       "1" => "0"
      time_partitioning.0.field: "imported_timestamp" => "" (forces new resource)
      time_partitioning.0.type:  "DAY" => ""
      type:                      "TABLE" => <computed>
```

**Comment by de-code** [comment]
> On `staging` it wants to destroy and recreate these two new tables

Okay, not a problem in `staging`.

**Comment by giorgiosironi** [comment]
Doesn't seem to happen in `prod`, so blindly applying everything.

**Comment by giorgiosironi** [comment]
Applied to `staging`.

**Comment by giorgiosironi** [comment]
Uh, now that I have imported the 4 tables from `prod` the diff would destroy 2 of them:
[prod.txt](https://github.com/elifesciences/builder/files/3712994/prod.txt)

**Comment by de-code** [comment]
(My PR in `ci` was now passing)

**Comment by de-code** [comment]
> Uh, now that I have imported the 4 tables from `prod` the diff would destroy 2 of them:
> [prod.txt](https://github.com/elifesciences/builder/files/3712994/prod.txt)

Okay, I should have read the issue in `staging` more carefully. Somehow I read it in reverse I think... the table was already partitioned but now it wants to remove that partitioning (which we don't want). I think Michael created that table manually with partitioning. Can we configure partitioning via builder?

If not, we should probably hold of applying to `prod` until it does.

**Comment by giorgiosironi** [comment]
Doing some changes to add it, but cannot test the diff as the `prod` server is going up and down and doesn't respond. Will add unit tests for the moment.

**Comment by giorgiosironi** [comment]
Restarting from `ci`.

**Comment by giorgiosironi** [comment]
`ci` dropped the 2 and recreated them again (with partitioning I believe).

**Comment by giorgiosironi** [comment]
Applied to `prod`, merging on green.

**Comment by de-code** [comment]
Fantastic, thank you.

**Pull request merged**
