### PR TITLE
threadbare, sync with latest changes (SCP backend)

### PR DESCRIPTION
**Pull request by lsh-0**
* switches downloads and uploads to use SCP from using SFTP
* adds support for running local commands with `sudo`

### CODE REVIEW

**Comment by lsh-0** [comment]
The big change here is that you can specify SFTP or SCP to transfer files. 

Paramiko uses SFTP so that is what I went with with threadbare, however Paramiko uses it's own SFTP implementation which is faster than native. I'm not sure if it's native SFTP or the Parallel-SSH library's usage of it, but performance degrades as the file sizes get larger. SCP on the other hand outperforms Paramko SFTP and native SFTP.

I encountered one issue with uploading via SCP during CI that I couldn't replicate locally, possibly because I'm still using magnetic spinning discs, but there was a delay between uploading a file, having it report that is was successfully completed, checking the file and finding it missing. Performing a check that the remote file exists after the upload successfully completed seemed to fix this. SFTP never suffered from this.

Another factor that may have contributed to the original issue is that Parallel-SSH was returning a pool of `gevent` 'greenlets' that weren't being forced to join the main process. They now are. My gut feeling is this wasn't the real cause but may have obfuscated stacktraces.

**Comment by lsh-0** [comment]
once this is merged in could you attempt to replicate that problem you were having in Alfred, @giorgiosironi ?

**Comment by giorgiosironi** [comment]
As far as I know reproducing the problem just means running https://alfred.elifesciences.org/job/process/job/process-journal-cms-restore-continuumtest/ which has been modified to pass in the `BLDR_BACKEND=threadbase` environment variable.

**Comment by lsh-0** [comment]
> which has been modified to pass in the BLDR_BACKEND=threadbase environment variable.

alright then, I'll give that a go once Alfred has finished updating itself.

**Comment by lsh-0** [comment]
It's a bust. Debugging these alfred scripts to figure out what they're doing

**Pull request merged**
