### PR TITLE
ElastiCache: private Redis node with customizable version and type

### PR DESCRIPTION
**Pull request by giorgiosironi**
Will expand upon this after experimenting with real eLife projects stack instances.

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Test instance up as `journal--cachetest`:
```
elife@continuumtest--journal:~$ redis-cli -h jou-el-1h7ejszvo06ps.yq8mzu.0001.use1.cache.amazonaws.com
jou-el-1h7ejszvo06ps.yq8mzu.0001.use1.cache.amazonaws.com:6379> KEYS ALL
(empty list or set)
```
(connecting from there as there is no redis-cli on `journal--cachetest`)

**Comment by giorgiosironi** [comment]
Missing context: every journal EC2 instance has its own local Redis. It uses it for caches, but this could be more efficient if we had a centralized cache that all journal--prod instances can use and invalidate. Moreover, having a centralized Redis allows to use the cache to store session information, while now we have to resort to client affinity and send the user to the same instance if he is in a session (used sparingly in forms but will be used more in the future, for logging in).

**Comment by lsh-0** [comment]
ah - righto. thanks

**Comment by thewilkybarkid** [comment]
Also allows the cache to persist across deploys, so the HTTP cache isn't invalided on every highstate.

**Pull request merged**
