### PR TITLE
upgrades salt to 2018.3. salt-bootstrap uses py3

### PR DESCRIPTION
**Pull request by lsh-0**
follow up PR to python2 removal branch

cc @giorgiosironi

### CODE REVIEW

**Comment by lsh-0** [comment]
of course. changed base.

there are still [two outstanding PRs](https://github.com/elifesciences/issues/issues/5267) blocking the upgrade to Salt (master-server and elife-libraries), so I'll deal with them before returning to this

**Comment by lsh-0** [comment]
both of those dependencies are merged by the elife-libraries python3 issue with mysqldb remains. 

the next-salt alt config has been implemented, but the error won't be recreated until py3 is used (this PR), so bit of an awkward bug for now. Investigating it before I merge this.

**Comment by lsh-0** [comment]
it looks like my blockers to upgrading python3+salt 2018.3 have now been resolved. 

I'll map out a plan to upgrade the master server and then the minions

**Comment by giorgiosironi** [comment]
This script contains a reference to this PPA for Python 2.7:
https://launchpad.net/~jonathonf/+archive/ubuntu/python-2.7
which now states it has been removed from public access. I fear this one will break very soon, or is already broken then. Any way to verify?

**Comment by lsh-0** [comment]
> Any way to verify?

I'll take a look today.

I'm about a centimeter away from upgrading Salt. I just need to finish testing those libraries, upgrade master-server, make sure loris can survive without that PPA until the container version can be tested properly and we'll be off of it.

I have a ticket here tracking all the python2 things left to purge: https://github.com/elifesciences/issues/issues/4726

**Pull request merged**
