### PR TITLE
Downgrading Fabric for Mac compatibility

### PR DESCRIPTION
**Pull request by giorgiosironi**
Newer version explodes on trying to compile something with Clang.

### CODE REVIEW

**Comment by giorgiosironi** [comment]
This works on the Mac I have here, but should be checked on the actual Macs we use everyday.

**Comment by lsh-0** [comment]
does anything on here help? http://www.fabfile.org/installing.html#dependencies

**Comment by giorgiosironi** [comment]
Yes, there are a few because people use them to develop for iOS:
http://www.macincloud.com/
https://xcloud.me/
Would still make sense to let people use this version on their Macs until the issue with the latest Fabric is resolved (this was the Fabric version in use until last week)

**Comment by lsh-0** [comment]
thanks for links. I've made a tweak, if you're happy with it, please merge.

**Comment by giorgiosironi** [comment]
Tested installation on a Mac, seems to work, merging.

**Pull request merged**
