### PR TITLE
added person_v2 schema

### PR DESCRIPTION
**Pull request by de-code**
URL doesn't seem to work because it probably doesn't receive my authentication details.

We currently don't use `person_v2` but should switch to it when we think the quality is good enough.

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Will get in https://github.com/elifesciences/builder/pull/455 first.

**Comment by giorgiosironi** [comment]
Applying to `data-pipeline--ci` also shows an update in place for `person`:
```
oogle_bigquery_table.ci_person: Modifying... (ID: elife-data-pipeline:ci.person)
  schema: "[{\"mode\":\"NULLABLE\",\"name\":\"email\",\"type\":\"STRING\"},{\"fields\":[{\"mode\":\"NULLABLE\",\"name\":\"reference_type\",\"type\":\"STRING\"},{\"mode\":\
"NULLABLE\",\"name\":\"reference_value\",\"type\":\"STRING\"}],\"mode\":\"REPEATED\",\"name\":\"external_references\",\"type\":\"RECORD\"},{\"mode\":\"NULLABLE\",\"name\":
\"first_name\",\"type\":\"STRING\"},{\"mode\":\"NULLABLE\",\"name\":\"institution\",\"type\":\"STRING\"},{\"mode\":\"NULLABLE\",\"name\":\"last_name\",\"type\":\"STRING\"}
,{\"mode\":\"NULLABLE\",\"name\":\"middle_name\",\"type\":\"STRING\"},{\"mode\":\"NULLABLE\",\"name\":\"modified_timestamp\",\"type\":\"TIMESTAMP\"},{\"mode\":\"NULLABLE\"
,\"name\":\"person_id\",\"type\":\"STRING\"},{\"fields\":[{\"mode\":\"NULLABLE\",\"name\":\"source_filename\",\"type\":\"STRING\"}],\"mode\":\"NULLABLE\",\"name\":\"proven
ance\",\"type\":\"RECORD\"},{\"fields\":[{\"mode\":\"NULLABLE\",\"name\":\"role_name\",\"type\":\"STRING\"}],\"mode\":\"REPEATED\",\"name\":\"roles\",\"type\":\"RECORD\"},
{\"mode\":\"NULLABLE\",\"name\":\"secondary_email\",\"type\":\"STRING\"},{\"mode\":\"NULLABLE\",\"name\":\"title\",\"type\":\"STRING\"},{\"fields\":[{\"mode\":\"NULLABLE\"
,\"name\":\"address_line_1\",\"type\":\"STRING\"},{\"mode\":\"NULLABLE\",\"name\":\"address_line_2\",\"type\":\"STRING\"},{\"mode\":\"NULLABLE\",\"name\":\"address_type\",
\"type\":\"STRING\"},{\"mode\":\"NULLABLE\",\"name\":\"area\",\"type\":\"STRING\"},{\"mode\":\"NULLABLE\",\"name\":\"city\",\"type\":\"STRING\"},{\"mode\":\"NULLABLE\",\"n
ame\":\"country\",\"type\":\"STRING\"},{\"mode\":\"NULLABLE\",\"name\":\"department\",\"type\":\"STRING\"},{\"mode\":\"NULLABLE\",\"name\":\"end_timestamp\",\"type\":\"STR
ING\"},{\"mode\":\"NULLABLE\",\"name\":\"postal_code\",\"type\":\"STRING\"},{\"mode\":\"NULLABLE\",\"name\":\"start_timestamp\",\"type\":\"TIMESTAMP\"}],\"mode\":\"REPEATE
D\",\"name\":\"addresses\",\"type\":\"RECORD\"}]" => "[{\"fields\":[{\"mode\":\"NULLABLE\",\"name\":\"address_line_1\",\"type\":\"STRING\"},{\"mode\":\"NULLABLE\",\"name\"
:\"address_line_2\",\"type\":\"STRING\"},{\"mode\":\"NULLABLE\",\"name\":\"address_type\",\"type\":\"STRING\"},{\"mode\":\"NULLABLE\",\"name\":\"area\",\"type\":\"STRING\"
},{\"mode\":\"NULLABLE\",\"name\":\"city\",\"type\":\"STRING\"},{\"mode\":\"NULLABLE\",\"name\":\"country\",\"type\":\"STRING\"},{\"mode\":\"NULLABLE\",\"name\":\"departme
nt\",\"type\":\"STRING\"},{\"mode\":\"NULLABLE\",\"name\":\"end_timestamp\",\"type\":\"STRING\"},{\"mode\":\"NULLABLE\",\"name\":\"postal_code\",\"type\":\"STRING\"},{\"mo
de\":\"NULLABLE\",\"name\":\"start_timestamp\",\"type\":\"TIMESTAMP\"}],\"mode\":\"REPEATED\",\"name\":\"addresses\",\"type\":\"RECORD\"},{\"mode\":\"NULLABLE\",\"name\":\
"email\",\"type\":\"STRING\"},{\"fields\":[{\"mode\":\"NULLABLE\",\"name\":\"reference_type\",\"type\":\"STRING\"},{\"mode\":\"NULLABLE\",\"name\":\"reference_value\",\"ty
pe\":\"STRING\"}],\"mode\":\"REPEATED\",\"name\":\"external_references\",\"type\":\"RECORD\"},{\"mode\":\"NULLABLE\",\"name\":\"first_name\",\"type\":\"STRING\"},{\"mode\"
:\"NULLABLE\",\"name\":\"institution\",\"type\":\"STRING\"},{\"mode\":\"NULLABLE\",\"name\":\"last_name\",\"type\":\"STRING\"},{\"mode\":\"NULLABLE\",\"name\":\"middle_nam
e\",\"type\":\"STRING\"},{\"mode\":\"NULLABLE\",\"name\":\"modified_timestamp\",\"type\":\"TIMESTAMP\"},{\"mode\":\"NULLABLE\",\"name\":\"person_id\",\"type\":\"STRING\"},
{\"fields\":[{\"mode\":\"NULLABLE\",\"name\":\"source_filename\",\"type\":\"STRING\"}],\"mode\":\"NULLABLE\",\"name\":\"provenance\",\"type\":\"RECORD\"},{\"fields\":[{\"$
ode\":\"NULLABLE\",\"name\":\"role_name\",\"type\":\"STRING\"}],\"mode\":\"REPEATED\",\"name\":\"roles\",\"type\":\"RECORD\"},{\"mode\":\"NULLABLE\",\"name\":\"secondary_$
mail\",\"type\":\"STRING\"},{\"mode\":\"NULLABLE\",\"name\":\"title\",\"type\":\"STRING\"}]"
```

**Comment by giorgiosironi** [comment]
`data-pipeline--staging` only needs to add the new table.

**Comment by giorgiosironi** [comment]
However, fails because the table is already there:
```
* google_bigquery_table.staging_person_v2: googleapi: Error 409: Already Exists: Table elife-data-pipeline:staging.person_v2, duplicate
```

**Comment by giorgiosironi** [comment]
Trying:
```
[giorgio@Newton:~/code/builder/.cfn/terraform/data-pipeline--staging]$ terraform import google_bigquery_table.staging_person_v2 elife-data-pipeline:staging.person_v2
```
which seems to have worked as no changes to apply are detected.

Moving to `prod`...

**Comment by giorgiosironi** [comment]
Same treatment applied successfully to `prod`.

**Comment by de-code** [comment]
Will it now automatically update the environments or will you still need to run the command manually?

**Pull request merged**
