### PR TITLE
ELPP-3586 Drop packer and custom Vagrant boxes

### PR DESCRIPTION
**Pull request by giorgiosironi**
See ticket, freeing up builder from unused integrations in favor of new responsibilities.

I'll be using this PR [to test out Danger](https://elifesciences.atlassian.net/browse/ELPP-3309), strange comments may appear.

### CODE REVIEW

**Comment by giorgiosironi** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Danger saying there's something wrong
  </td>
    </tr>
  </tbody>
</table>



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  Changed Files in this PR: 
 - .gitignore- src/buildercore/bakery.py- src/buildercore/core.py- src/fabfile.py- update.sh
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by giorgiosironi** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  Changed Files in this PR: 
 - .gitignore- src/buildercore/bakery.py- src/buildercore/core.py- src/fabfile.py- update.sh
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by giorgiosironi** [comment]
(Ignore the `Danger` commit status)

**Comment by lsh-0** [comment]
> freeing up builder from unused integrations in favor of new responsibilities.

it's not like we're running out of space ;) you don't need to justify dead code removal

**Comment by lsh-0** [comment]
ticket https://elifesciences.atlassian.net/browse/ELPP-3586

**Comment by lsh-0** [comment]
how come you're keeping the ami_name in bakery.py? (are we using it somewhere?)

**Comment by giorgiosironi** [comment]
> how come you're keeping the ami_name in bakery.py? (are we using it somewhere?)

Yes, https://github.com/elifesciences/builder/pull/277/files#diff-164dee6c4a4e8e6d84251f1cc1caf921R21

**Pull request merged**
