### PR TITLE
Added support for creating S3 buckets

### PR DESCRIPTION
**Pull request by giorgiosironi**

### CODE REVIEW

**Comment by giorgiosironi** [comment]
@lsh-0 I have used this from my own machine to add some S3 buckets for the elife-bot without recreating the stack instances. Old versions of the builder should just ignore the additional S3 metadata in contexts until merged.

**Comment by lsh-0** [comment]
can we add support for the deletion policy like we do with RDS? I want it made explicit that the contents of the S3 bucket will be destroyed when the stack is torn down

http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-deletionpolicy.html

**Comment by giorgiosironi** [comment]
Added the default retention in the template, which for this bucket is `Delete` as it's a temporary folder for silent corrections. However I also made it configurable so that other buckets can use the `Retain` policy in the future.

**Comment by giorgiosironi** [comment]
Used for the silent corrections bucket, needed for the new published CDN-related bucket, merging.

**Pull request merged**
