### PR TITLE
improved linting with pyflakes.

### PR DESCRIPTION
**Pull request by lsh-0**

### CODE REVIEW

**Comment by giorgiosironi** [comment]
:+1: seems like a lot of unused imports

**Comment by lsh-0** [comment]
there is another tool, called `flake8` that combined pyflakes with some parts of pep8, but I'm not _too_ concerned about whitespace and line-too-long errors.

**Comment by lsh-0** [comment]
given this is still a PR, I might try and bump some warnings to errors somehow.

**Comment by lsh-0** [comment]
ok - this should be ready for merging now if everything passes.

the lint script now does this:
* very quick pyflakes call
* quick, errors-only, pylint pass
* less quick comprehensive pylint pass (no outstanding linting problem at time of commit)

@giorgiosironi if you could confirm this function name change doesn't affect anything from your end, I'd be grateful: https://github.com/elifesciences/builder/pull/50/files#diff-11aa22c619b41fcc4ac5151f83decddcL144

I've also had to more precisely specify some of the exception being thrown. I'm less confident on these, but they're still pretty broad.

**Comment by giorgiosironi** [comment]
No problem with the function name change, reading through the rest.

**Comment by giorgiosironi** [comment]
:+1:

**Pull request merged**
